### ISSUE TITLE
Prusti 2.2.1 Example

### ISSUE THREAD

**Issue by EmilyOng** [EmilyOng/AlgebraicEffect#10]
Code example from Section 2.2.1 in Modular Specification and Verification of Closures in Rust:

```rust
let mut i = 1;
let mut j = 2; // j is captured by (mutable) reference below:
let mut cl = |x: &mut i32| -> i32 { j += *x; *x += 1; j + *x };
let r = cl(&mut i);
assert_eq!(i, 2); // the closure's side effect on its argument
assert_eq!(j, 3); // the closure's side effect on its captured state
assert_eq!(r, 5); // the closure's result
```

<details>
<summary>Direct translation</summary>

Currently, this form of let bindings are not expected.

```ocaml
let closure_with_effect ()
(*@ ex i; ex j; ens i->2*j->3 /\ res=5 @*)
= let i = ref 1 and j = ref 2 in
  let cl x =
    j := !j + !x;
    x := !x + 1;
    !j + !x in
  cl i
```
</details>

Using Heifer:

```ocaml
let closure_with_effect ()
(*@ ex i; ex j; ens i->2*j->3 /\ res=5 @*)
= let i = ref 1 in
  let j = ref 2 in
  let cl x =
    j := !j + !x;
    x := !x + 1;
    !j + !x in
  cl i
```

<details>
<summary>Staged Specification for cl(x, res)</summary>

```
cl(x,res) = req x->a * j->b  // If x != j
                  ens j->b+a * x->a+1 /\  res=b+a+a+1
                  req x->a /\ x=j // If x = j (sep. logic notation)
                  ens j->2a+1 /\ res=2a+1+a+1
```
</details>

**Comment by EmilyOng** [comment]
For this to work, we need to fix the missing bindings for `j`, as it was mentioned [earlier](https://github.com/EmilyOng/AlgebraicEffect/issues/2#issuecomment-1861984248). For example:

```ocaml
let let_with_and ()
= let i = ref 1 and j = ref 2 in
  ()
```
The parsed program is:
```ocaml
let i = ref 1 in                     
()
```
And, the normed specification is `ex v2; Norm(v2->1/\res=())`.

The tokens are:
```
LET LIDENT LPAREN RPAREN EQUAL LET LIDENT EQUAL LIDENT INT AND LIDENT EQUAL LIDENT INT IN LPAREN RPAREN EOF
```

**Comment by EmilyOng** [comment]
In `parser.mly`, a consideration for `expr AND expr` may be needed [here](https://github.com/songyahui/AlgebraicEffect/blob/StagedSL/parsing/parser.mly#L2185), or there might be some other parts I'm still looking at.

**Comment by dariusf** [comment]
You can work around this for now like this, as the bindings aren't mutually recursive:

```ocaml
let let_with_and ()
= let i = ref 1 in
  let j = ref 2 in
  ()
```

The bug is in how we translate the [OCaml AST](https://github.com/songyahui/AlgebraicEffect/blob/StagedSL/parsing/parsetree.ml#L280) to our `core_lang` - we're [only using the first value binding](https://github.com/songyahui/AlgebraicEffect/blob/StagedSL/parsing/hiplib.ml#L724).

If you would like to try fixing this, I think it's fine to translate it to the workaround for now, and leave mutual recursion for later.
