### ISSUE TITLE
Check syntax of specification

### ISSUE THREAD

**Issue by EmilyOng** [EmilyOng/AlgebraicEffect#5]
Using these: https://github.com/EmilyOng/AlgebraicEffect/blob/StagedSL/parsing/lexer.mll#L39?

**Comment by dariusf** [comment]
That file has the concrete syntax of tokens. The grammar (with tokens shown more abstractly) is [here](https://github.com/EmilyOng/AlgebraicEffect/blob/StagedSL/parsing/parser.mly#L2727).
